language: ruby
sudo: false
cache: bundler
rvm:
  - "1.9.3"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
gemfile:
  - gemfiles/faraday-0.8.gemfile
  - gemfiles/faraday-1.0.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/faraday-1.0.gemfile
      rvm: "1.9.3"
    - gemfile: gemfiles/faraday-1.0.gemfile
      rvm: "2.0"
    - gemfile: gemfiles/faraday-1.0.gemfile
      rvm: "2.1"
    - gemfile: gemfiles/faraday-1.0.gemfile
      rvm: "2.2"
before_install:
  - gem update bundler
script:
  - bundle exec rspec
